name: Saludando

on:
  push:
    branches:
      - main
      - develop

jobs:
  saludo:
    runs-on: ubuntu-latest
    steps:
        if: github.ref == 'refs/heads/main'
      - name: Saludo desde main
        run: echo "Hola desde main, mi nombre es Gerson Portal"
        if: github.ref == 'refs/heads/develop'
      - name: Saludo desde develop
        run: echo "Hola desde develop, mi nombre es Gerson Portal"
